
package screens;

import java.awt.event.*;
import java.awt.*;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author JesTa
 */
public class Blockchain extends javax.swing.JFrame {

    /**
     * Creates new form Blockchain
     */
    public Blockchain() {
        initComponents();
    }
    
    Boolean check = false;
    Boolean check2 = false;
    Boolean check3 = false;
    Boolean check4 = false;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        block1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        nonceBlock1 = new javax.swing.JTextField();
        preHashBlock1 = new javax.swing.JTextField();
        hashBlock1 = new javax.swing.JTextField();
        mineBlock1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataBlock1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        block2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        nonceBlock2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hashBlock2 = new javax.swing.JTextField();
        mineBlock2 = new javax.swing.JButton();
        preHashBlock2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataBlock2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RUBIKS - EDUCATIONAL UI");
        setMinimumSize(new java.awt.Dimension(1280, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1425, 600));

        pnlRoot.setMinimumSize(new java.awt.Dimension(1425, 600));
        pnlRoot.setPreferredSize(new java.awt.Dimension(1190, 600));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSide.setBackground(new java.awt.Color(7, 33, 43));
        pnlSide.setPreferredSize(new java.awt.Dimension(80, 0));

        jPanel1.setBackground(new java.awt.Color(7, 33, 43));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 170));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_rubik's_cube_20px.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        pnlSide.add(jPanel1);

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_home_20px.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlSide.add(jButton2);

        jButton3.setBackground(new java.awt.Color(0, 204, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_document_20px.png"))); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlSide.add(jButton3);

        jButton4.setBackground(new java.awt.Color(0, 204, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_cube_20px.png"))); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnlSide.add(jButton4);

        jButton5.setBackground(new java.awt.Color(0, 204, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_blockchain_technology_20px.png"))); // NOI18N
        jButton5.setPreferredSize(new java.awt.Dimension(40, 40));
        pnlSide.add(jButton5);

        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(3, 47, 64));
        pnlCenter.setMinimumSize(new java.awt.Dimension(1000, 600));
        pnlCenter.setPreferredSize(new java.awt.Dimension(1110, 600));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        block1.setBackground(new java.awt.Color(3, 47, 64));
        block1.setMinimumSize(new java.awt.Dimension(800, 600));
        block1.setPreferredSize(new java.awt.Dimension(600, 530));
        block1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BLOCK:");
        block1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 65, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("#");
        block1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 65, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NONCE:");
        block1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 95, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRE. HASH:");
        block1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 367, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HASH:");
        block1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 402, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("GENESIS");
        block1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 64, 368, -1));

        nonceBlock1.setEditable(false);
        nonceBlock1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nonceBlock1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        block1.add(nonceBlock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 94, 368, -1));

        preHashBlock1.setEditable(false);
        preHashBlock1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        preHashBlock1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        block1.add(preHashBlock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 366, 470, 30));

        hashBlock1.setEditable(false);
        hashBlock1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        hashBlock1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        block1.add(hashBlock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 401, 470, 30));

        mineBlock1.setBackground(new java.awt.Color(0, 204, 255));
        mineBlock1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        mineBlock1.setText("MINE");
        mineBlock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mineBlock1ActionPerformed(evt);
            }
        });
        block1.add(mineBlock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 443, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DATA:");
        block1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 124, -1, -1));

        dataBlock1.setColumns(20);
        dataBlock1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        dataBlock1.setLineWrap(true);
        dataBlock1.setRows(5);
        dataBlock1.setToolTipText("");
        dataBlock1.setName(""); // NOI18N
        dataBlock1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dataBlock1KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(dataBlock1);
        dataBlock1.getAccessibleContext().setAccessibleName("");
        dataBlock1.getAccessibleContext().setAccessibleDescription("");

        block1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 124, 368, 231));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Blockchain.jpg"))); // NOI18N
        block1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 310, 620, 310));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Blockchain.jpg"))); // NOI18N
        block1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 620, 310));

        pnlCenter.add(block1, java.awt.BorderLayout.WEST);

        block2.setBackground(new java.awt.Color(3, 47, 64));
        block2.setMinimumSize(new java.awt.Dimension(300, 610));
        block2.setPreferredSize(new java.awt.Dimension(530, 530));
        block2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BLOCK:");
        block2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 65, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("#");
        block2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 65, 20, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NONCE:");
        block2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 94, 60, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA:");
        block2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 124, 60, -1));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField6.setText("1");
        block2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 64, 380, -1));

        nonceBlock2.setEditable(false);
        nonceBlock2.setBackground(new java.awt.Color(255, 255, 255));
        nonceBlock2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nonceBlock2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nonceBlock2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nonceBlock2CaretUpdate(evt);
            }
        });
        block2.add(nonceBlock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 94, 380, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PRE. HASH:");
        block2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 367, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("HASH:");
        block2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 402, -1, -1));

        hashBlock2.setEditable(false);
        hashBlock2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        hashBlock2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        block2.add(hashBlock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 401, 470, 30));

        mineBlock2.setBackground(new java.awt.Color(0, 204, 255));
        mineBlock2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        mineBlock2.setText("MINE");
        mineBlock2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mineBlock2ActionPerformed(evt);
            }
        });
        block2.add(mineBlock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 443, -1, -1));

        preHashBlock2.setEditable(false);
        preHashBlock2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        preHashBlock2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        block2.add(preHashBlock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 366, 470, 30));

        dataBlock2.setColumns(20);
        dataBlock2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        dataBlock2.setLineWrap(true);
        dataBlock2.setRows(5);
        dataBlock2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dataBlock2KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(dataBlock2);

        block2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 124, 380, 231));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Blockchain.jpg"))); // NOI18N
        block2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 650, 310));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Blockchain.jpg"))); // NOI18N
        block2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 310));

        pnlCenter.add(block2, java.awt.BorderLayout.CENTER);

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        Principal p = new Principal();
        p.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        close();
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        close();
        Documentation d = new Documentation();
        d.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        close();
        Block b = new Block();
        b.setVisible(true);
        close();
        Bloque bk = new Bloque();
        b.nonceBlock.setText(bk.toString(bk.getNonce()));
        //b.dataBlock.setText(bk.getData());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void mineBlock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mineBlock1ActionPerformed
        // TODO add your handling code here:
        Bloque b = new Bloque();
        String data = dataBlock1.getText();
        if(check) {
            this.nonceBlock1.setText(b.toString(b.Nonce()));
            this.hashBlock1.setText(b.Hash(data));
            this.dataBlock2.setText(b.getData());
            this.nonceBlock2.setText(b.toString(b.Nonce()));
            this.preHashBlock2.setText(this.hashBlock1.getText());
            nonceBlock1.setBackground(Color.green);
            //dataBlock1.setBackground(Color.green);
            hashBlock1.setBackground(Color.green);
            check = false;
            if(check2) {
                nonceBlock2.setBackground(Color.green);
                preHashBlock2.setBackground(Color.green);
            }
        }
    }//GEN-LAST:event_mineBlock1ActionPerformed

    private void mineBlock2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mineBlock2ActionPerformed
        // TODO add your handling code here:
        Bloque b = new Bloque();
        String data = dataBlock2.getText();
        
        if(check2 || check3) {
            this.hashBlock2.setText(b.Hash(data));
            this.hashBlock2.setBackground(Color.green);
            this.nonceBlock2.setBackground(Color.green);
            this.preHashBlock2.setBackground(Color.green);
            check2 = false;
            check3 = true;
            
        }
    }//GEN-LAST:event_mineBlock2ActionPerformed

    private void dataBlock1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataBlock1KeyTyped
        // TODO add your handling code here:
        check = true;
        nonceBlock1.setBackground(Color.red);
        //nonceBlock2.setBackground(Color.red);
        hashBlock1.setBackground(Color.red);
        if(check2) {
            nonceBlock2.setBackground(Color.red);
            preHashBlock2.setBackground(Color.red);            
        } else if(check3) {
            nonceBlock2.setBackground(Color.red);
            preHashBlock2.setBackground(Color.red);
            hashBlock2.setBackground(Color.red);
            //check3 = true;
        }               
    }//GEN-LAST:event_dataBlock1KeyTyped

    private void dataBlock2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataBlock2KeyTyped
        // TODO add your handling code here:        
        
        if(check3) {
            //nonceBlock1.setBackground(Color.red);
            //hashBlock1.setBackground(Color.red);
            //nonceBlock2.setBackground(Color.red);
            //preHashBlock2.setBackground(Color.red);
            hashBlock2.setBackground(Color.red);  
            
             if(check4) {
            nonceBlock2.setBackground(Color.red);
            preHashBlock2.setBackground(Color.red);
            hashBlock2.setBackground(Color.red);  
            check4 = true;
             }
        }check4 = true;
    }//GEN-LAST:event_dataBlock2KeyTyped

    private void nonceBlock2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nonceBlock2CaretUpdate
        // TODO add your handling code here:
        check2 = true;
        //check3 = true;
    }//GEN-LAST:event_nonceBlock2CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Blockchain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Blockchain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Blockchain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Blockchain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Blockchain().setVisible(true);
            }
        });
    }
    
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    public JTextArea getDataBlock1() {
        return dataBlock1;
    }

    public void setDataBlock1(JTextArea dataBlock1) {
        this.dataBlock1 = dataBlock1;
    }

    public JTextArea getDataBlock2() {
        return dataBlock2;
    }

    public void setDataBlock2(JTextArea dataBlock2) {
        this.dataBlock2 = dataBlock2;
    }

    public JTextField getHashBlock1() {
        return hashBlock1;
    }

    public void setHashBlock1(JTextField hashBlock1) {
        this.hashBlock1 = hashBlock1;
    }

    public JTextField getHashBlock2() {
        return hashBlock2;
    }

    public void setHashBlock2(JTextField hashBlock2) {
        this.hashBlock2 = hashBlock2;
    }

    public JTextField getNonceBlock1() {
        return nonceBlock1;
    }

    public void setNonceBlock1(JTextField nonceBlock1) {
        this.nonceBlock1 = nonceBlock1;
    }

    public JTextField getNonceBlock2() {
        return nonceBlock2;
    }

    public void setNonceBlock2(JTextField nonceBlock2) {
        this.nonceBlock2 = nonceBlock2;
    }

    public JTextField getPreHashBlock1() {
        return preHashBlock1;
    }

    public void setPreHashBlock1(JTextField preHashBlock1) {
        this.preHashBlock1 = preHashBlock1;
    }

    public JTextField getPreHashBlock2() {
        return preHashBlock2;
    }

    public void setPreHashBlock2(JTextField preHashBlock2) {
        this.preHashBlock2 = preHashBlock2;
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel block1;
    private javax.swing.JPanel block2;
    public javax.swing.JTextArea dataBlock1;
    public javax.swing.JTextArea dataBlock2;
    public javax.swing.JTextField hashBlock1;
    public javax.swing.JTextField hashBlock2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    public javax.swing.JButton mineBlock1;
    public javax.swing.JButton mineBlock2;
    public javax.swing.JTextField nonceBlock1;
    public javax.swing.JTextField nonceBlock2;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    public javax.swing.JTextField preHashBlock1;
    public javax.swing.JTextField preHashBlock2;
    // End of variables declaration//GEN-END:variables
}
